[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
fs_permissions = [
  { access = "read", path = "./script/deployments" },
  { access = "read", path = "./images/"}
]

[lint]
exclude_lints  = [
  "unsafe-cheatcode",
  "mixed-case-function"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
